[identities]
argon-root = "age19c2lj8tp448qz2nmj2fhjhz3ss2w0zuhpudhx8k6e4e3pjkknemqunutd3"
argon-tobias = "age1gh8taacs5kv8qet0vyrash9xx9rcvgemwuhevg6q0eqczp73545qd3eaf3"
bak = "age1kttfv4zpvv0cshe8q7lvakycytn34pja9pcy4ylq94kw90k3yfwsxja79j"
bwpm-FP2CYXKY2V-tobiashapp = "age1myzyfx9x07s8657sn7529qw8nfa93vt8g6f457zksgnfxftgtf5qc5l6ls"
gamer-tobias = "age1xmwue6azg27l7kwsjr7a84gax5ed7tzdzfw4c3vz3aejr539tpdswmlpt8"
krypton-root = "age1vheh9hvezl0k2fe7wpfjnfp6ajcezz78jlhxj6wvzxdvkte4lfys03ktuq"
krypton-tobias = "age1r2maar050kkskxpaestrd738dpphptp886mdt4kta2p3mup3mc9s4r4020"
neon-root = "age16xxy8wcp8as2uc7v04fncsa7x257luygse94khp7c5mglh4wnggs8t4sk5"
neon-tobias = "age1m0cyz2y5vyztmx04x0xheyhhy8uwf53yem6dafmce3hsugwhfp4q0lg267"
pixel7a-nix-on-droid = "age18f5h39n0pcr82knus3tem305kclj75rf3yy3jahtda80ym53rsmqmpc6uh"
R2026-tobiashapp = "age1jc36ddc7cfqskjs56nfy6q8vz5p9wsaqfe5f0hzds76grkzwdazsymhu8e"
xenon-root = "age1glu7paaertha2q28whxehvgn7euj52z5pka0edlrp6pnhqypvcmqm2lg64"
xenon-tobias = "age1dxhjmnugds3263vsh02zrxagxal5x25ycs3xpueja7yfvcx8lves8p5rkv"

[[paths]]
glob = "secrets/ssh/private/*"
identities = [
    "bak",
    "bwpm-FP2CYXKY2V-tobiashapp",
    "gamer-tobias",
    "neon-tobias",
    "pixel7a-nix-on-droid",
    "R2026-tobiashapp",
]

[[paths]]
glob = "secrets/ssh/vcs/*"
identities = [
    "argon-tobias",
    "bak",
    "bwpm-FP2CYXKY2V-tobiashapp",
    "gamer-tobias",
    "krypton-tobias",
    "neon-tobias",
    "pixel7a-nix-on-droid",
    "R2026-tobiashapp",
    "xenon-tobias",
]

[[paths]]
glob = "secrets/argon/*"
identities = [ "bak", "argon-root" ]

[[paths]]
glob = "secrets/krypton/*"
identities = [ "bak", "krypton-root" ]

[[paths]]
glob = "secrets/neon/*"
identities = [ "bak", "neon-root" ]

[[paths]]
glob = "secrets/xenon/*"
identities = [ "bak", "xenon-root" ]
